export const LOAD_ROLES_START = "LOAD_ROLES_START"
export const LOAD_ROLES_SUCCESS = "LOAD_ROLES_SUCCESS"
export const LOAD_ROLES_ERROR = "LOAD_ROLES_ERROR"

export const ADD_NEW_ROLE_START = 'ADD_NEW_ROLE_START'
export const ADD_NEW_ROLE_SUCCESS = 'ADD_NEW_ROLE_SUCCESS'
export const ADD_NEW_ROLE_ERROR = 'ADD_NEW_ROLE_ERROR'

export const UPDATE_ROLE_START = 'UPDATE_ROLE_START'
export const UPDATE_ROLE_SUCCESS = 'UPDATE_ROLE_SUCCESS'
export const UPDATE_ROLE_ERROR = 'UPDATE_ROLE_ERROR'

export const DELETE_ROLE_START = 'DELETE_ROLE_START'
export const DELETE_ROLE_SUCCESS = 'DELETE_ROLE_SUCCESS'
export const DELETE_ROLE_ERROR = 'DELETE_ROLE_ERROR'